services:
  streamlit-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
    environment:
      - STREAMLIT_SERVER_PORT=8080
      - STREAMLIT_SERVER_HEADLESS=true
    restart: unless-stopped